import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import { TContext } from '../../main/ts/ifaces'
import {
  format,
  getLockfileType,
  parse,
  refurbish,
} from '../../main/ts/lockfile'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const fixtures = path.resolve(__dirname, '../fixtures')

// A WRONG checksum is fatal — `yarn install` refuses the lockfile with YN0018
// ("checksum mismatch") and the user cannot install at all. A MISSING one is not:
// yarn computes and writes it. So every expectation here is either yarn's own
// value or nothing, and the values below are yarn's, read out of real locks that
// `yarn install` wrote (not recorded from our own output — that would only pin
// whatever we happen to emit, including a wrong value).
//
// Guards the 11.0.5 regression: the checksum recipe rebuilt the zip with the
// right cacheKey prefix but the wrong archive bytes, so it filled a plausible,
// wrong hash in both the bare (cacheKey 8) and the `10c0/` era.
const YARN_TRUTH = {
  // qiwi/mware — yarn 3.x, berry v6, cacheKey 8: checksums carry no prefix.
  8: 'e3f1c368778b16f9e7e4fd4199d04913bba9b017c37fbca7642b3613ebefcf3b18a4bd55e5f7074dc023fc95c96bd265f72114044e62cebae7f9a0f53bc36ace',
  // qiwi/buildstamp — yarn 4.9.4, berry v8, cacheKey 10c0 (STORE).
  '10c0':
    '10c0/855fb70b093d1d9643ddc12ea76dca90dc9d9cdd7f82c08ee8b9325c0dc5748faf3c82e2047ced5dcaa8b26e58f7903900be2628d0380a222c02d79d8de385df',
}

const tarballs = {
  tarball: async (name: string, version: string) => {
    try {
      return new Uint8Array(
        readFileSync(path.join(fixtures, 'tarballs', `${name}-${version}.tgz`)),
      )
    } catch {
      return undefined
    }
  },
}
const ctx = (): TContext =>
  ({
    flags: { silent: true },
    tarballSource: tarballs,
    cwd: process.cwd(),
  }) as unknown as TContext

const checksumOf = (text: string, name: string): string | undefined =>
  /\n {2}checksum: (\S+)/.exec(
    text.split('\n\n').find((b) => b.startsWith(`"${name}@npm:`)) ?? '',
  )?.[1]

// The recompute is calibrated against an entry whose checksum the lock already
// carries, so each case needs one anchor of its own era — and its tarball on disk.
const lockWith = (
  version: number,
  cacheKey: string,
  anchor: { name: string; version: string; checksum: string },
) => `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: ${version}
  cacheKey: ${cacheKey}

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    diff: 4.0.4
    ${anchor.name}: ${anchor.version}
  languageName: unknown
  linkType: soft

"diff@npm:4.0.4":
  version: 4.0.4
  resolution: "diff@npm:4.0.4"
  languageName: node
  linkType: hard

"${anchor.name}@npm:${anchor.version}":
  version: ${anchor.version}
  resolution: "${anchor.name}@npm:${anchor.version}"
  checksum: ${anchor.checksum}
  languageName: node
  linkType: hard
`

const anchorFrom = (fixture: string, name: string) => {
  const lock = readFileSync(
    path.join(fixtures, 'lockfile', fixture, 'yarn.lock'),
    'utf-8',
  )
  const checksum = checksumOf(lock, name)
  expect(checksum, `${name} anchor checksum in ${fixture}`).toBeTruthy()
  return checksum!
}

const fill = async (lock: string): Promise<string | undefined> => {
  const fmt = getLockfileType(lock)
  const out = format(await refurbish(parse(lock, fmt), fmt, ctx()), fmt)
  return checksumOf(out, 'diff')
}

describe('refurbish — checksums match yarn or stay absent', () => {
  const minimist = {
    name: 'minimist',
    version: '1.2.5',
    checksum: anchorFrom('v3', 'minimist'),
  }
  const colorName = {
    name: 'color-name',
    version: '1.1.4',
    checksum: anchorFrom('v4', 'color-name'),
  }

  it('bare era (berry v6, cacheKey 8): byte-for-byte what yarn wrote', async () => {
    await expect(fill(lockWith(6, '8', minimist))).resolves.toBe(YARN_TRUTH[8])
  })

  it('current era (berry v8, cacheKey 10c0): byte-for-byte what yarn wrote', async () => {
    await expect(fill(lockWith(8, '10c0', colorName))).resolves.toBe(
      YARN_TRUTH['10c0'],
    )
  })

  // cacheKey 9 is a yarn 4.0-rc window whose archives we cannot reproduce; the
  // only safe answer is silence, and `yarn install` fills it in.
  it('cacheKey 9 (yarn 4.0-rc): deferred, never guessed', async () => {
    await expect(fill(lockWith(7, '9', minimist))).resolves.toBeUndefined()
  })
})
